// Mocks generated by Mockito 5.3.2 from annotations
// in lomba_frontend/test/presentation/sidedrawer/bloc/sidedrawer_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:dartz/dartz.dart' as _i3;
import 'package:lomba_frontend/core/failures.dart' as _i8;
import 'package:lomba_frontend/data/models/session_model.dart' as _i11;
import 'package:lomba_frontend/domain/entities/orga.dart' as _i13;
import 'package:lomba_frontend/domain/entities/session.dart' as _i17;
import 'package:lomba_frontend/domain/repositories/local_repository.dart'
    as _i2;
import 'package:lomba_frontend/domain/repositories/login_repository.dart'
    as _i5;
import 'package:lomba_frontend/domain/repositories/orga_repository.dart' as _i4;
import 'package:lomba_frontend/domain/usecases/local/get_has_login.dart'
    as _i14;
import 'package:lomba_frontend/domain/usecases/local/get_session_status.dart'
    as _i10;
import 'package:lomba_frontend/domain/usecases/login/change_orga.dart' as _i16;
import 'package:lomba_frontend/domain/usecases/orgas/get_orga.dart' as _i15;
import 'package:lomba_frontend/domain/usecases/orgas/get_orgasbyuser.dart'
    as _i12;
import 'package:lomba_frontend/domain/usecases/sidedrawer/do_logoff.dart'
    as _i9;
import 'package:lomba_frontend/domain/usecases/sidedrawer/get_side_options.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLocalRepository_0 extends _i1.SmartFake
    implements _i2.LocalRepository {
  _FakeLocalRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrgaRepository_2 extends _i1.SmartFake
    implements _i4.OrgaRepository {
  _FakeOrgaRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLoginRepository_3 extends _i1.SmartFake
    implements _i5.LoginRepository {
  _FakeLoginRepository_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetSideOptions].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSideOptions extends _i1.Mock implements _i6.GetSideOptions {
  MockGetSideOptions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LocalRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeLocalRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.LocalRepository);
  @override
  _i7.Future<_i3.Either<_i8.Failure, List<String>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i7.Future<_i3.Either<_i8.Failure, List<String>>>.value(
            _FakeEither_1<_i8.Failure, List<String>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i7.Future<_i3.Either<_i8.Failure, List<String>>>);
}

/// A class which mocks [DoLogOff].
///
/// See the documentation for Mockito's code generation for more information.
class MockDoLogOff extends _i1.Mock implements _i9.DoLogOff {
  MockDoLogOff() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LocalRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeLocalRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.LocalRepository);
  @override
  _i7.Future<_i3.Either<_i8.Failure, bool>> execute() => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i7.Future<_i3.Either<_i8.Failure, bool>>.value(
            _FakeEither_1<_i8.Failure, bool>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i7.Future<_i3.Either<_i8.Failure, bool>>);
}

/// A class which mocks [GetSession].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSession extends _i1.Mock implements _i10.GetSession {
  MockGetSession() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LocalRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeLocalRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.LocalRepository);
  @override
  _i7.Future<_i3.Either<_i8.Failure, _i11.SessionModel>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue:
            _i7.Future<_i3.Either<_i8.Failure, _i11.SessionModel>>.value(
                _FakeEither_1<_i8.Failure, _i11.SessionModel>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i7.Future<_i3.Either<_i8.Failure, _i11.SessionModel>>);
}

/// A class which mocks [GetOrgasByUser].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetOrgasByUser extends _i1.Mock implements _i12.GetOrgasByUser {
  MockGetOrgasByUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.OrgaRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeOrgaRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.OrgaRepository);
  @override
  _i7.Future<_i3.Either<_i8.Failure, List<_i13.Orga>>> execute(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [userId],
        ),
        returnValue: _i7.Future<_i3.Either<_i8.Failure, List<_i13.Orga>>>.value(
            _FakeEither_1<_i8.Failure, List<_i13.Orga>>(
          this,
          Invocation.method(
            #execute,
            [userId],
          ),
        )),
      ) as _i7.Future<_i3.Either<_i8.Failure, List<_i13.Orga>>>);
}

/// A class which mocks [GetHasLogIn].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetHasLogIn extends _i1.Mock implements _i14.GetHasLogIn {
  MockGetHasLogIn() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LocalRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeLocalRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.LocalRepository);
  @override
  _i7.Future<_i3.Either<_i8.Failure, bool>> execute() => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i7.Future<_i3.Either<_i8.Failure, bool>>.value(
            _FakeEither_1<_i8.Failure, bool>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i7.Future<_i3.Either<_i8.Failure, bool>>);
}

/// A class which mocks [GetOrga].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetOrga extends _i1.Mock implements _i15.GetOrga {
  MockGetOrga() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.OrgaRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeOrgaRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.OrgaRepository);
  @override
  _i7.Future<_i3.Either<_i8.Failure, _i13.Orga>> execute(String? orgaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [orgaId],
        ),
        returnValue: _i7.Future<_i3.Either<_i8.Failure, _i13.Orga>>.value(
            _FakeEither_1<_i8.Failure, _i13.Orga>(
          this,
          Invocation.method(
            #execute,
            [orgaId],
          ),
        )),
      ) as _i7.Future<_i3.Either<_i8.Failure, _i13.Orga>>);
}

/// A class which mocks [ChangeOrga].
///
/// See the documentation for Mockito's code generation for more information.
class MockChangeOrga extends _i1.Mock implements _i16.ChangeOrga {
  MockChangeOrga() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.LoginRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeLoginRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.LoginRepository);
  @override
  _i7.Future<_i3.Either<_i8.Failure, _i17.Session>> execute(
    String? username,
    String? orgaId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            username,
            orgaId,
          ],
        ),
        returnValue: _i7.Future<_i3.Either<_i8.Failure, _i17.Session>>.value(
            _FakeEither_1<_i8.Failure, _i17.Session>(
          this,
          Invocation.method(
            #execute,
            [
              username,
              orgaId,
            ],
          ),
        )),
      ) as _i7.Future<_i3.Either<_i8.Failure, _i17.Session>>);
}
