// Mocks generated by Mockito 5.3.2 from annotations
// in lomba_frontend/test/features/login/data/repositories/login_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:lomba_frontend/features/login/data/datasources/localcache_data_source.dart'
    as _i5;
import 'package:lomba_frontend/features/login/data/datasources/remote_data_source.dart'
    as _i3;
import 'package:lomba_frontend/features/login/data/models/token_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTokenModel_0 extends _i1.SmartFake implements _i2.TokenModel {
  _FakeTokenModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDataSource extends _i1.Mock implements _i3.RemoteDataSource {
  MockRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.TokenModel> getAuthenticate(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAuthenticate,
          [
            username,
            password,
          ],
        ),
        returnValue: _i4.Future<_i2.TokenModel>.value(_FakeTokenModel_0(
          this,
          Invocation.method(
            #getAuthenticate,
            [
              username,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i2.TokenModel>);
}

/// A class which mocks [LocalCacheDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalCacheDataSource extends _i1.Mock
    implements _i5.LocalCacheDataSource {
  MockLocalCacheDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.TokenModel> getSavedToken() => (super.noSuchMethod(
        Invocation.method(
          #getSavedToken,
          [],
        ),
        returnValue: _i4.Future<_i2.TokenModel>.value(_FakeTokenModel_0(
          this,
          Invocation.method(
            #getSavedToken,
            [],
          ),
        )),
      ) as _i4.Future<_i2.TokenModel>);
  @override
  _i4.Future<void> saveToken(_i2.TokenModel? token) => (super.noSuchMethod(
        Invocation.method(
          #saveToken,
          [token],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<bool> hasToken() => (super.noSuchMethod(
        Invocation.method(
          #hasToken,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
