// Mocks generated by Mockito 5.3.2 from annotations
// in lomba_frontend/test/presentation/flow/bloc/flow_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:lomba_frontend/core/failures.dart' as _i6;
import 'package:lomba_frontend/domain/entities/workflow/flow.dart' as _i7;
import 'package:lomba_frontend/domain/repositories/flow_repository.dart' as _i2;
import 'package:lomba_frontend/domain/usecases/flow/get_flow.dart' as _i4;
import 'package:lomba_frontend/domain/usecases/flow/get_flows.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFlowRepository_0 extends _i1.SmartFake
    implements _i2.FlowRepository {
  _FakeFlowRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetFlow].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFlow extends _i1.Mock implements _i4.GetFlow {
  @override
  _i2.FlowRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeFlowRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeFlowRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.FlowRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Flow>> execute(String? flowId) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [flowId],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Flow>>.value(
            _FakeEither_1<_i6.Failure, _i7.Flow>(
          this,
          Invocation.method(
            #execute,
            [flowId],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, _i7.Flow>>.value(
                _FakeEither_1<_i6.Failure, _i7.Flow>(
          this,
          Invocation.method(
            #execute,
            [flowId],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Flow>>);
}

/// A class which mocks [GetFlows].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFlows extends _i1.Mock implements _i8.GetFlows {
  @override
  _i2.FlowRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeFlowRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeFlowRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.FlowRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Flow>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, List<_i7.Flow>>>.value(
            _FakeEither_1<_i6.Failure, List<_i7.Flow>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.Flow>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.Flow>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Flow>>>);
}
