// Mocks generated by Mockito 5.3.2 from annotations
// in lomba_frontend/test/data/repositories/login_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_guid/flutter_guid.dart' as _i8;
import 'package:lomba_frontend/data/datasources/local_data_source.dart' as _i6;
import 'package:lomba_frontend/data/datasources/login_data_source.dart' as _i4;
import 'package:lomba_frontend/data/datasources/user_data_source.dart' as _i7;
import 'package:lomba_frontend/data/models/session_model.dart' as _i2;
import 'package:lomba_frontend/data/models/user_model.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSessionModel_0 extends _i1.SmartFake implements _i2.SessionModel {
  _FakeSessionModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserModel_1 extends _i1.SmartFake implements _i3.UserModel {
  _FakeUserModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDataSource extends _i1.Mock implements _i4.RemoteDataSource {
  MockRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.SessionModel> getAuthenticate(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAuthenticate,
          [
            username,
            password,
          ],
        ),
        returnValue: _i5.Future<_i2.SessionModel>.value(_FakeSessionModel_0(
          this,
          Invocation.method(
            #getAuthenticate,
            [
              username,
              password,
            ],
          ),
        )),
      ) as _i5.Future<_i2.SessionModel>);
  @override
  _i5.Future<bool> registerUser(
    _i3.UserModel? usermodel,
    String? orgaId,
    String? password,
    String? role,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerUser,
          [
            usermodel,
            orgaId,
            password,
            role,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
  @override
  _i5.Future<_i2.SessionModel> changeOrga(
    String? username,
    String? orgaId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeOrga,
          [
            username,
            orgaId,
          ],
        ),
        returnValue: _i5.Future<_i2.SessionModel>.value(_FakeSessionModel_0(
          this,
          Invocation.method(
            #changeOrga,
            [
              username,
              orgaId,
            ],
          ),
        )),
      ) as _i5.Future<_i2.SessionModel>);
  @override
  _i5.Future<_i2.SessionModel> getAuthenticateGoogle(
    _i3.UserModel? user,
    String? googleToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAuthenticateGoogle,
          [
            user,
            googleToken,
          ],
        ),
        returnValue: _i5.Future<_i2.SessionModel>.value(_FakeSessionModel_0(
          this,
          Invocation.method(
            #getAuthenticateGoogle,
            [
              user,
              googleToken,
            ],
          ),
        )),
      ) as _i5.Future<_i2.SessionModel>);
}

/// A class which mocks [LocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDataSource extends _i1.Mock implements _i6.LocalDataSource {
  MockLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.SessionModel> getSavedSession() => (super.noSuchMethod(
        Invocation.method(
          #getSavedSession,
          [],
        ),
        returnValue: _i5.Future<_i2.SessionModel>.value(_FakeSessionModel_0(
          this,
          Invocation.method(
            #getSavedSession,
            [],
          ),
        )),
      ) as _i5.Future<_i2.SessionModel>);
  @override
  _i5.Future<bool> saveSession(_i2.SessionModel? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSession,
          [session],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
  @override
  _i5.Future<bool> hasSession() => (super.noSuchMethod(
        Invocation.method(
          #hasSession,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
  @override
  _i5.Future<bool> cleanSession() => (super.noSuchMethod(
        Invocation.method(
          #cleanSession,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
  @override
  _i5.Future<bool> saveStartRedirectLogin() => (super.noSuchMethod(
        Invocation.method(
          #saveStartRedirectLogin,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
  @override
  _i5.Future<bool> getIfRedirectLogin() => (super.noSuchMethod(
        Invocation.method(
          #getIfRedirectLogin,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
  @override
  _i5.Future<bool> cleanRedirectLogin() => (super.noSuchMethod(
        Invocation.method(
          #cleanRedirectLogin,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [UserRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRemoteDataSource extends _i1.Mock
    implements _i7.UserRemoteDataSource {
  MockUserRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.UserModel>> getUsers(
    String? orgaId,
    String? filter,
    String? fieldOrder,
    double? pageNumber,
    int? pageSize,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUsers,
          [
            orgaId,
            filter,
            fieldOrder,
            pageNumber,
            pageSize,
          ],
        ),
        returnValue: _i5.Future<List<_i3.UserModel>>.value(<_i3.UserModel>[]),
      ) as _i5.Future<List<_i3.UserModel>>);
  @override
  _i5.Future<_i3.UserModel> getUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [userId],
        ),
        returnValue: _i5.Future<_i3.UserModel>.value(_FakeUserModel_1(
          this,
          Invocation.method(
            #getUser,
            [userId],
          ),
        )),
      ) as _i5.Future<_i3.UserModel>);
  @override
  _i5.Future<_i3.UserModel> addUser(_i3.UserModel? user) => (super.noSuchMethod(
        Invocation.method(
          #addUser,
          [user],
        ),
        returnValue: _i5.Future<_i3.UserModel>.value(_FakeUserModel_1(
          this,
          Invocation.method(
            #addUser,
            [user],
          ),
        )),
      ) as _i5.Future<_i3.UserModel>);
  @override
  _i5.Future<bool> deleteUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [userId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
  @override
  _i5.Future<bool> enableUser(
    String? userId,
    bool? enableOrDisable,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #enableUser,
          [
            userId,
            enableOrDisable,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
  @override
  _i5.Future<_i3.UserModel> updateUser(
    String? userId,
    _i3.UserModel? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [
            userId,
            user,
          ],
        ),
        returnValue: _i5.Future<_i3.UserModel>.value(_FakeUserModel_1(
          this,
          Invocation.method(
            #updateUser,
            [
              userId,
              user,
            ],
          ),
        )),
      ) as _i5.Future<_i3.UserModel>);
  @override
  _i5.Future<_i3.UserModel?> existsUser(
    String? userId,
    String? username,
    String? email,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #existsUser,
          [
            userId,
            username,
            email,
          ],
        ),
        returnValue: _i5.Future<_i3.UserModel?>.value(),
      ) as _i5.Future<_i3.UserModel?>);
  @override
  _i5.Future<List<_i3.UserModel>> getUsersNotInOrga(
    String? orgaId,
    List<dynamic>? order,
    int? pageNumber,
    int? pageSize,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUsersNotInOrga,
          [
            orgaId,
            order,
            pageNumber,
            pageSize,
          ],
        ),
        returnValue: _i5.Future<List<_i3.UserModel>>.value(<_i3.UserModel>[]),
      ) as _i5.Future<List<_i3.UserModel>>);
  @override
  _i5.Future<bool> updateUserPassword(
    String? userId,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserPassword,
          [
            userId,
            password,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [Guid].
///
/// See the documentation for Mockito's code generation for more information.
class MockGuid extends _i1.Mock implements _i8.Guid {
  MockGuid() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get value => (super.noSuchMethod(
        Invocation.getter(#value),
        returnValue: '',
      ) as String);
}
