// Mocks generated by Mockito 5.3.2 from annotations
// in lomba_frontend/test/features/sidedrawer/presentation/bloc/sidedrawer_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:lomba_frontend/core/domain/repositories/local_repository.dart'
    as _i2;
import 'package:lomba_frontend/core/failures.dart' as _i6;
import 'package:lomba_frontend/features/sidedrawer/domain/usecases/do_logoff.dart'
    as _i7;
import 'package:lomba_frontend/features/sidedrawer/domain/usecases/get_side_options.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLocalRepository_0 extends _i1.SmartFake
    implements _i2.LocalRepository {
  _FakeLocalRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetSideOptions].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSideOptions extends _i1.Mock implements _i4.GetSideOptions {
  MockGetSideOptions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LocalRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeLocalRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.LocalRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<String>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, List<String>>>.value(
            _FakeEither_1<_i6.Failure, List<String>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<String>>>);
}

/// A class which mocks [DoLogOff].
///
/// See the documentation for Mockito's code generation for more information.
class MockDoLogOff extends _i1.Mock implements _i7.DoLogOff {
  MockDoLogOff() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LocalRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeLocalRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.LocalRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> execute() => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
            _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, bool>>);
}
